// <auto-generated />
using System;
using DeveLanCacheUI_Backend.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeveLanCacheUI_Backend.Migrations
{
    [DbContext(typeof(DeveLanCacheUIDbContext))]
    [Migration("20250506203509_AsyncLogEntryTable")]
    partial class AsyncLogEntryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DeveLanCacheUI_Backend.Db.DbModels.DbAsyncLogEntryProcessingQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AsyncLogEntryProcessingQueueItems");
                });

            modelBuilder.Entity("DeveLanCacheUI_Backend.Db.DbModels.DbDownloadEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheHitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CacheMissBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("DownloadIdentifier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadIdentifierString")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CacheIdentifier");

                    b.HasIndex("ClientIp");

                    b.ToTable("DownloadEvents");
                });

            modelBuilder.Entity("DeveLanCacheUI_Backend.Db.DbModels.DbSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DeveLanCacheUI_Backend.Db.DbModels.DbSteamDepot", b =>
                {
                    b.Property<uint>("SteamDepotId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SteamAppId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SteamDepotId", "SteamAppId");

                    b.ToTable("SteamDepots");
                });

            modelBuilder.Entity("DeveLanCacheUI_Backend.Db.DbModels.DbSteamManifest", b =>
                {
                    b.Property<uint>("DepotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ManifestBytesSize")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TotalCompressedSize")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TotalUncompressedSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueManifestIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DepotId", "CreationTime");

                    b.HasIndex("UniqueManifestIdentifier")
                        .IsUnique();

                    b.ToTable("SteamManifests");
                });

            modelBuilder.Entity("DeveLanCacheUI_Backend.Db.DbModels.DbAsyncLogEntryProcessingQueueItem", b =>
                {
                    b.OwnsOne("DeveLanCacheUI_Backend.LogReading.Models.LanCacheLogEntryRaw", "LanCacheLogEntryRaw", b1 =>
                        {
                            b1.Property<int>("DbAsyncLogEntryProcessingQueueItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BodyBytesSent")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<long>("BodyBytesSentLong")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CacheIdentifier")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DateTime")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DownloadIdentifier")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ForwardedFor")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("HttpRange")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("OriginalLogLine")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ParseException")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Referer")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("RemoteAddress")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("RemoteUser")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Request")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("TimeLocal")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("UpstreamCacheStatus")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("UserAgent")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("DbAsyncLogEntryProcessingQueueItemId");

                            b1.ToTable("AsyncLogEntryProcessingQueueItems");

                            b1.WithOwner()
                                .HasForeignKey("DbAsyncLogEntryProcessingQueueItemId");
                        });

                    b.Navigation("LanCacheLogEntryRaw")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
