namespace DeveLanCacheUI_Backend.ProtoTest
{
    // <auto-generated>
    //   This file was generated by a tool; you should avoid making direct changes.
    //   Consider using 'partial classes' to extend these types
    //   Input: my.proto
    // </auto-generated>

    #region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
    [global::ProtoBuf.ProtoContract()]
    public partial class ContentManifestPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mappings")]
        public global::System.Collections.Generic.List<FileMapping> Mappings { get; } = new global::System.Collections.Generic.List<FileMapping>();

        [global::ProtoBuf.ProtoContract()]
        public partial class FileMapping : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"filename")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Filename
            {
                get => __pbn__Filename ?? "";
                set => __pbn__Filename = value;
            }
            public bool ShouldSerializeFilename() => __pbn__Filename != null;
            public void ResetFilename() => __pbn__Filename = null;
            private string __pbn__Filename;

            [global::ProtoBuf.ProtoMember(2, Name = @"size")]
            public ulong Size
            {
                get => __pbn__Size.GetValueOrDefault();
                set => __pbn__Size = value;
            }
            public bool ShouldSerializeSize() => __pbn__Size != null;
            public void ResetSize() => __pbn__Size = null;
            private ulong? __pbn__Size;

            [global::ProtoBuf.ProtoMember(3, Name = @"flags")]
            public uint Flags
            {
                get => __pbn__Flags.GetValueOrDefault();
                set => __pbn__Flags = value;
            }
            public bool ShouldSerializeFlags() => __pbn__Flags != null;
            public void ResetFlags() => __pbn__Flags = null;
            private uint? __pbn__Flags;

            [global::ProtoBuf.ProtoMember(4, Name = @"sha_filename")]
            public byte[] ShaFilename
            {
                get => __pbn__ShaFilename;
                set => __pbn__ShaFilename = value;
            }
            public bool ShouldSerializeShaFilename() => __pbn__ShaFilename != null;
            public void ResetShaFilename() => __pbn__ShaFilename = null;
            private byte[] __pbn__ShaFilename;

            [global::ProtoBuf.ProtoMember(5, Name = @"sha_content")]
            public byte[] ShaContent
            {
                get => __pbn__ShaContent;
                set => __pbn__ShaContent = value;
            }
            public bool ShouldSerializeShaContent() => __pbn__ShaContent != null;
            public void ResetShaContent() => __pbn__ShaContent = null;
            private byte[] __pbn__ShaContent;

            [global::ProtoBuf.ProtoMember(6, Name = @"chunks")]
            public global::System.Collections.Generic.List<ChunkData> Chunks { get; } = new global::System.Collections.Generic.List<ChunkData>();

            [global::ProtoBuf.ProtoMember(7, Name = @"linktarget")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Linktarget
            {
                get => __pbn__Linktarget ?? "";
                set => __pbn__Linktarget = value;
            }
            public bool ShouldSerializeLinktarget() => __pbn__Linktarget != null;
            public void ResetLinktarget() => __pbn__Linktarget = null;
            private string __pbn__Linktarget;

            [global::ProtoBuf.ProtoContract()]
            public partial class ChunkData : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"sha")]
                public byte[] Sha
                {
                    get => __pbn__Sha;
                    set => __pbn__Sha = value;
                }
                public bool ShouldSerializeSha() => __pbn__Sha != null;
                public void ResetSha() => __pbn__Sha = null;
                private byte[] __pbn__Sha;

                [global::ProtoBuf.ProtoMember(2, Name = @"crc", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
                public uint Crc
                {
                    get => __pbn__Crc.GetValueOrDefault();
                    set => __pbn__Crc = value;
                }
                public bool ShouldSerializeCrc() => __pbn__Crc != null;
                public void ResetCrc() => __pbn__Crc = null;
                private uint? __pbn__Crc;

                [global::ProtoBuf.ProtoMember(3, Name = @"offset")]
                public ulong Offset
                {
                    get => __pbn__Offset.GetValueOrDefault();
                    set => __pbn__Offset = value;
                }
                public bool ShouldSerializeOffset() => __pbn__Offset != null;
                public void ResetOffset() => __pbn__Offset = null;
                private ulong? __pbn__Offset;

                [global::ProtoBuf.ProtoMember(4, Name = @"cb_original")]
                public uint CbOriginal
                {
                    get => __pbn__CbOriginal.GetValueOrDefault();
                    set => __pbn__CbOriginal = value;
                }
                public bool ShouldSerializeCbOriginal() => __pbn__CbOriginal != null;
                public void ResetCbOriginal() => __pbn__CbOriginal = null;
                private uint? __pbn__CbOriginal;

                [global::ProtoBuf.ProtoMember(5, Name = @"cb_compressed")]
                public uint CbCompressed
                {
                    get => __pbn__CbCompressed.GetValueOrDefault();
                    set => __pbn__CbCompressed = value;
                }
                public bool ShouldSerializeCbCompressed() => __pbn__CbCompressed != null;
                public void ResetCbCompressed() => __pbn__CbCompressed = null;
                private uint? __pbn__CbCompressed;

            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContentManifestMetadata : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"depot_id")]
        public uint DepotId
        {
            get => __pbn__DepotId.GetValueOrDefault();
            set => __pbn__DepotId = value;
        }
        public bool ShouldSerializeDepotId() => __pbn__DepotId != null;
        public void ResetDepotId() => __pbn__DepotId = null;
        private uint? __pbn__DepotId;

        [global::ProtoBuf.ProtoMember(2, Name = @"gid_manifest")]
        public ulong GidManifest
        {
            get => __pbn__GidManifest.GetValueOrDefault();
            set => __pbn__GidManifest = value;
        }
        public bool ShouldSerializeGidManifest() => __pbn__GidManifest != null;
        public void ResetGidManifest() => __pbn__GidManifest = null;
        private ulong? __pbn__GidManifest;

        [global::ProtoBuf.ProtoMember(3, Name = @"creation_time")]
        public uint CreationTime
        {
            get => __pbn__CreationTime.GetValueOrDefault();
            set => __pbn__CreationTime = value;
        }
        public bool ShouldSerializeCreationTime() => __pbn__CreationTime != null;
        public void ResetCreationTime() => __pbn__CreationTime = null;
        private uint? __pbn__CreationTime;

        [global::ProtoBuf.ProtoMember(4, Name = @"filenames_encrypted")]
        public bool FilenamesEncrypted
        {
            get => __pbn__FilenamesEncrypted.GetValueOrDefault();
            set => __pbn__FilenamesEncrypted = value;
        }
        public bool ShouldSerializeFilenamesEncrypted() => __pbn__FilenamesEncrypted != null;
        public void ResetFilenamesEncrypted() => __pbn__FilenamesEncrypted = null;
        private bool? __pbn__FilenamesEncrypted;

        [global::ProtoBuf.ProtoMember(5, Name = @"cb_disk_original")]
        public ulong CbDiskOriginal
        {
            get => __pbn__CbDiskOriginal.GetValueOrDefault();
            set => __pbn__CbDiskOriginal = value;
        }
        public bool ShouldSerializeCbDiskOriginal() => __pbn__CbDiskOriginal != null;
        public void ResetCbDiskOriginal() => __pbn__CbDiskOriginal = null;
        private ulong? __pbn__CbDiskOriginal;

        [global::ProtoBuf.ProtoMember(6, Name = @"cb_disk_compressed")]
        public ulong CbDiskCompressed
        {
            get => __pbn__CbDiskCompressed.GetValueOrDefault();
            set => __pbn__CbDiskCompressed = value;
        }
        public bool ShouldSerializeCbDiskCompressed() => __pbn__CbDiskCompressed != null;
        public void ResetCbDiskCompressed() => __pbn__CbDiskCompressed = null;
        private ulong? __pbn__CbDiskCompressed;

        [global::ProtoBuf.ProtoMember(7, Name = @"unique_chunks")]
        public uint UniqueChunks
        {
            get => __pbn__UniqueChunks.GetValueOrDefault();
            set => __pbn__UniqueChunks = value;
        }
        public bool ShouldSerializeUniqueChunks() => __pbn__UniqueChunks != null;
        public void ResetUniqueChunks() => __pbn__UniqueChunks = null;
        private uint? __pbn__UniqueChunks;

        [global::ProtoBuf.ProtoMember(8, Name = @"crc_encrypted")]
        public uint CrcEncrypted
        {
            get => __pbn__CrcEncrypted.GetValueOrDefault();
            set => __pbn__CrcEncrypted = value;
        }
        public bool ShouldSerializeCrcEncrypted() => __pbn__CrcEncrypted != null;
        public void ResetCrcEncrypted() => __pbn__CrcEncrypted = null;
        private uint? __pbn__CrcEncrypted;

        [global::ProtoBuf.ProtoMember(9, Name = @"crc_clear")]
        public uint CrcClear
        {
            get => __pbn__CrcClear.GetValueOrDefault();
            set => __pbn__CrcClear = value;
        }
        public bool ShouldSerializeCrcClear() => __pbn__CrcClear != null;
        public void ResetCrcClear() => __pbn__CrcClear = null;
        private uint? __pbn__CrcClear;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContentManifestSignature : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"signature")]
        public byte[] Signature
        {
            get => __pbn__Signature;
            set => __pbn__Signature = value;
        }
        public bool ShouldSerializeSignature() => __pbn__Signature != null;
        public void ResetSignature() => __pbn__Signature = null;
        private byte[] __pbn__Signature;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContentDeltaChunks : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"depot_id")]
        public uint DepotId
        {
            get => __pbn__DepotId.GetValueOrDefault();
            set => __pbn__DepotId = value;
        }
        public bool ShouldSerializeDepotId() => __pbn__DepotId != null;
        public void ResetDepotId() => __pbn__DepotId = null;
        private uint? __pbn__DepotId;

        [global::ProtoBuf.ProtoMember(2, Name = @"manifest_id_source")]
        public ulong ManifestIdSource
        {
            get => __pbn__ManifestIdSource.GetValueOrDefault();
            set => __pbn__ManifestIdSource = value;
        }
        public bool ShouldSerializeManifestIdSource() => __pbn__ManifestIdSource != null;
        public void ResetManifestIdSource() => __pbn__ManifestIdSource = null;
        private ulong? __pbn__ManifestIdSource;

        [global::ProtoBuf.ProtoMember(3, Name = @"manifest_id_target")]
        public ulong ManifestIdTarget
        {
            get => __pbn__ManifestIdTarget.GetValueOrDefault();
            set => __pbn__ManifestIdTarget = value;
        }
        public bool ShouldSerializeManifestIdTarget() => __pbn__ManifestIdTarget != null;
        public void ResetManifestIdTarget() => __pbn__ManifestIdTarget = null;
        private ulong? __pbn__ManifestIdTarget;

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<DeltaChunk> deltaChunks { get; } = new global::System.Collections.Generic.List<DeltaChunk>();

        [global::ProtoBuf.ProtoMember(5, Name = @"chunk_data_location")]
        [global::System.ComponentModel.DefaultValue(EContentDeltaChunkDataLocation.kEContentDeltaChunkDataLocationInProtobuf)]
        public EContentDeltaChunkDataLocation ChunkDataLocation
        {
            get => __pbn__ChunkDataLocation ?? EContentDeltaChunkDataLocation.kEContentDeltaChunkDataLocationInProtobuf;
            set => __pbn__ChunkDataLocation = value;
        }
        public bool ShouldSerializeChunkDataLocation() => __pbn__ChunkDataLocation != null;
        public void ResetChunkDataLocation() => __pbn__ChunkDataLocation = null;
        private EContentDeltaChunkDataLocation? __pbn__ChunkDataLocation;

        [global::ProtoBuf.ProtoContract()]
        public partial class DeltaChunk : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"sha_source")]
            public byte[] ShaSource
            {
                get => __pbn__ShaSource;
                set => __pbn__ShaSource = value;
            }
            public bool ShouldSerializeShaSource() => __pbn__ShaSource != null;
            public void ResetShaSource() => __pbn__ShaSource = null;
            private byte[] __pbn__ShaSource;

            [global::ProtoBuf.ProtoMember(2, Name = @"sha_target")]
            public byte[] ShaTarget
            {
                get => __pbn__ShaTarget;
                set => __pbn__ShaTarget = value;
            }
            public bool ShouldSerializeShaTarget() => __pbn__ShaTarget != null;
            public void ResetShaTarget() => __pbn__ShaTarget = null;
            private byte[] __pbn__ShaTarget;

            [global::ProtoBuf.ProtoMember(3, Name = @"size_original")]
            public uint SizeOriginal
            {
                get => __pbn__SizeOriginal.GetValueOrDefault();
                set => __pbn__SizeOriginal = value;
            }
            public bool ShouldSerializeSizeOriginal() => __pbn__SizeOriginal != null;
            public void ResetSizeOriginal() => __pbn__SizeOriginal = null;
            private uint? __pbn__SizeOriginal;

            [global::ProtoBuf.ProtoMember(4, Name = @"patch_method")]
            public uint PatchMethod
            {
                get => __pbn__PatchMethod.GetValueOrDefault();
                set => __pbn__PatchMethod = value;
            }
            public bool ShouldSerializePatchMethod() => __pbn__PatchMethod != null;
            public void ResetPatchMethod() => __pbn__PatchMethod = null;
            private uint? __pbn__PatchMethod;

            [global::ProtoBuf.ProtoMember(5, Name = @"chunk")]
            public byte[] Chunk
            {
                get => __pbn__Chunk;
                set => __pbn__Chunk = value;
            }
            public bool ShouldSerializeChunk() => __pbn__Chunk != null;
            public void ResetChunk() => __pbn__Chunk = null;
            private byte[] __pbn__Chunk;

            [global::ProtoBuf.ProtoMember(6, Name = @"size_delta")]
            public uint SizeDelta
            {
                get => __pbn__SizeDelta.GetValueOrDefault();
                set => __pbn__SizeDelta = value;
            }
            public bool ShouldSerializeSizeDelta() => __pbn__SizeDelta != null;
            public void ResetSizeDelta() => __pbn__SizeDelta = null;
            private uint? __pbn__SizeDelta;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum EContentDeltaChunkDataLocation
    {
        [global::ProtoBuf.ProtoEnum(Name = @"k_EContentDeltaChunkDataLocationInProtobuf")]
        kEContentDeltaChunkDataLocationInProtobuf = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"k_EContentDeltaChunkDataLocationAfterProtobuf")]
        kEContentDeltaChunkDataLocationAfterProtobuf = 1,
    }

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
    #endregion

}
